/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppTermsRouteImport } from './routes/_app/terms'
import { Route as AppTeamsRouteImport } from './routes/_app/teams'
import { Route as AppTeamRequestsRouteImport } from './routes/_app/team-requests'
import { Route as AppTeamInviteRouteImport } from './routes/_app/team-invite'
import { Route as AppTeamChatRouteImport } from './routes/_app/team-chat'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as AppSpinWheelRouteImport } from './routes/_app/spin-wheel'
import { Route as AppSignupRouteImport } from './routes/_app/signup'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRulesRouteImport } from './routes/_app/rules'
import { Route as AppProfileShopRouteImport } from './routes/_app/profile-shop'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMyTeamRouteImport } from './routes/_app/my-team'
import { Route as AppMatchesRouteImport } from './routes/_app/matches'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppForgotPasswordRouteImport } from './routes/_app/forgot-password'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppAntiCheatRouteImport } from './routes/_app/anti-cheat'
import { Route as AppTournamentsIndexRouteImport } from './routes/_app/tournaments/index'
import { Route as AppSupportIndexRouteImport } from './routes/_app/support.index'
import { Route as AppSpinWheelIndexRouteImport } from './routes/_app/spin-wheel/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users.$userId'
import { Route as AppTournamentsIdRouteImport } from './routes/_app/tournaments/$id'
import { Route as AppSupportTicketIdRouteImport } from './routes/_app/support.$ticketId'
import { Route as AppSpinWheelBuyRouteImport } from './routes/_app/spin-wheel/buy'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminTournamentsRouteImport } from './routes/_app/admin/tournaments'
import { Route as AppAdminSpinWheelRouteImport } from './routes/_app/admin/spin-wheel'
import { Route as AppAdminSiteSettingsRouteImport } from './routes/_app/admin/site-settings'
import { Route as AppAdminRegistrationsRouteImport } from './routes/_app/admin/registrations'
import { Route as AppAdminProfileShopRouteImport } from './routes/_app/admin/profile-shop'
import { Route as AppAdminPayoutsRouteImport } from './routes/_app/admin/payouts'
import { Route as AppAdminNotificationsRouteImport } from './routes/_app/admin/notifications'
import { Route as AppAdminMessagesRouteImport } from './routes/_app/admin/messages'
import { Route as AppAdminLeaderboardRouteImport } from './routes/_app/admin/leaderboard'
import { Route as AppAdminDepositsRouteImport } from './routes/_app/admin/deposits'
import { Route as AppAdminTicketsIndexRouteImport } from './routes/_app/admin/tickets.index'
import { Route as AppAdminTicketsTicketIdRouteImport } from './routes/_app/admin/tickets.$ticketId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRequestsRoute = AppTeamRequestsRouteImport.update({
  id: '/team-requests',
  path: '/team-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamInviteRoute = AppTeamInviteRouteImport.update({
  id: '/team-invite',
  path: '/team-invite',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamChatRoute = AppTeamChatRouteImport.update({
  id: '/team-chat',
  path: '/team-chat',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppSpinWheelRoute = AppSpinWheelRouteImport.update({
  id: '/spin-wheel',
  path: '/spin-wheel',
  getParentRoute: () => AppRoute,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileShopRoute = AppProfileShopRouteImport.update({
  id: '/profile-shop',
  path: '/profile-shop',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMyTeamRoute = AppMyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppForgotPasswordRoute = AppForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAntiCheatRoute = AppAntiCheatRouteImport.update({
  id: '/anti-cheat',
  path: '/anti-cheat',
  getParentRoute: () => AppRoute,
} as any)
const AppTournamentsIndexRoute = AppTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportIndexRoute = AppSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => AppRoute,
} as any)
const AppSpinWheelIndexRoute = AppSpinWheelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSpinWheelRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppTournamentsIdRoute = AppTournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportTicketIdRoute = AppSupportTicketIdRouteImport.update({
  id: '/support/$ticketId',
  path: '/support/$ticketId',
  getParentRoute: () => AppRoute,
} as any)
const AppSpinWheelBuyRoute = AppSpinWheelBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => AppSpinWheelRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTournamentsRoute = AppAdminTournamentsRouteImport.update({
  id: '/admin/tournaments',
  path: '/admin/tournaments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSpinWheelRoute = AppAdminSpinWheelRouteImport.update({
  id: '/admin/spin-wheel',
  path: '/admin/spin-wheel',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSiteSettingsRoute = AppAdminSiteSettingsRouteImport.update({
  id: '/admin/site-settings',
  path: '/admin/site-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRegistrationsRoute = AppAdminRegistrationsRouteImport.update({
  id: '/admin/registrations',
  path: '/admin/registrations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProfileShopRoute = AppAdminProfileShopRouteImport.update({
  id: '/admin/profile-shop',
  path: '/admin/profile-shop',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPayoutsRoute = AppAdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNotificationsRoute = AppAdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMessagesRoute = AppAdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLeaderboardRoute = AppAdminLeaderboardRouteImport.update({
  id: '/admin/leaderboard',
  path: '/admin/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDepositsRoute = AppAdminDepositsRouteImport.update({
  id: '/admin/deposits',
  path: '/admin/deposits',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTicketsIndexRoute = AppAdminTicketsIndexRouteImport.update({
  id: '/admin/tickets/',
  path: '/admin/tickets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTicketsTicketIdRoute = AppAdminTicketsTicketIdRouteImport.update({
  id: '/admin/tickets/$ticketId',
  path: '/admin/tickets/$ticketId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/anti-cheat': typeof AppAntiCheatRoute
  '/chat': typeof AppChatRoute
  '/contact': typeof AppContactRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/login': typeof AppLoginRoute
  '/matches': typeof AppMatchesRoute
  '/my-team': typeof AppMyTeamRoute
  '/notifications': typeof AppNotificationsRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/profile-shop': typeof AppProfileShopRoute
  '/rules': typeof AppRulesRoute
  '/settings': typeof AppSettingsRoute
  '/signup': typeof AppSignupRoute
  '/spin-wheel': typeof AppSpinWheelRouteWithChildren
  '/stats': typeof AppStatsRoute
  '/team-chat': typeof AppTeamChatRoute
  '/team-invite': typeof AppTeamInviteRoute
  '/team-requests': typeof AppTeamRequestsRoute
  '/teams': typeof AppTeamsRoute
  '/terms': typeof AppTermsRoute
  '/wallet': typeof AppWalletRoute
  '/admin/deposits': typeof AppAdminDepositsRoute
  '/admin/leaderboard': typeof AppAdminLeaderboardRoute
  '/admin/messages': typeof AppAdminMessagesRoute
  '/admin/notifications': typeof AppAdminNotificationsRoute
  '/admin/payouts': typeof AppAdminPayoutsRoute
  '/admin/profile-shop': typeof AppAdminProfileShopRoute
  '/admin/registrations': typeof AppAdminRegistrationsRoute
  '/admin/site-settings': typeof AppAdminSiteSettingsRoute
  '/admin/spin-wheel': typeof AppAdminSpinWheelRoute
  '/admin/tournaments': typeof AppAdminTournamentsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/spin-wheel/buy': typeof AppSpinWheelBuyRoute
  '/support/$ticketId': typeof AppSupportTicketIdRoute
  '/tournaments/$id': typeof AppTournamentsIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/spin-wheel/': typeof AppSpinWheelIndexRoute
  '/support/': typeof AppSupportIndexRoute
  '/tournaments/': typeof AppTournamentsIndexRoute
  '/admin/tickets/$ticketId': typeof AppAdminTicketsTicketIdRoute
  '/admin/tickets/': typeof AppAdminTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/anti-cheat': typeof AppAntiCheatRoute
  '/chat': typeof AppChatRoute
  '/contact': typeof AppContactRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/login': typeof AppLoginRoute
  '/matches': typeof AppMatchesRoute
  '/my-team': typeof AppMyTeamRoute
  '/notifications': typeof AppNotificationsRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/profile-shop': typeof AppProfileShopRoute
  '/rules': typeof AppRulesRoute
  '/settings': typeof AppSettingsRoute
  '/signup': typeof AppSignupRoute
  '/stats': typeof AppStatsRoute
  '/team-chat': typeof AppTeamChatRoute
  '/team-invite': typeof AppTeamInviteRoute
  '/team-requests': typeof AppTeamRequestsRoute
  '/teams': typeof AppTeamsRoute
  '/terms': typeof AppTermsRoute
  '/wallet': typeof AppWalletRoute
  '/': typeof AppIndexRoute
  '/admin/deposits': typeof AppAdminDepositsRoute
  '/admin/leaderboard': typeof AppAdminLeaderboardRoute
  '/admin/messages': typeof AppAdminMessagesRoute
  '/admin/notifications': typeof AppAdminNotificationsRoute
  '/admin/payouts': typeof AppAdminPayoutsRoute
  '/admin/profile-shop': typeof AppAdminProfileShopRoute
  '/admin/registrations': typeof AppAdminRegistrationsRoute
  '/admin/site-settings': typeof AppAdminSiteSettingsRoute
  '/admin/spin-wheel': typeof AppAdminSpinWheelRoute
  '/admin/tournaments': typeof AppAdminTournamentsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/spin-wheel/buy': typeof AppSpinWheelBuyRoute
  '/support/$ticketId': typeof AppSupportTicketIdRoute
  '/tournaments/$id': typeof AppTournamentsIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/spin-wheel': typeof AppSpinWheelIndexRoute
  '/support': typeof AppSupportIndexRoute
  '/tournaments': typeof AppTournamentsIndexRoute
  '/admin/tickets/$ticketId': typeof AppAdminTicketsTicketIdRoute
  '/admin/tickets': typeof AppAdminTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/anti-cheat': typeof AppAntiCheatRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/forgot-password': typeof AppForgotPasswordRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/matches': typeof AppMatchesRoute
  '/_app/my-team': typeof AppMyTeamRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/profile-shop': typeof AppProfileShopRoute
  '/_app/rules': typeof AppRulesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/signup': typeof AppSignupRoute
  '/_app/spin-wheel': typeof AppSpinWheelRouteWithChildren
  '/_app/stats': typeof AppStatsRoute
  '/_app/team-chat': typeof AppTeamChatRoute
  '/_app/team-invite': typeof AppTeamInviteRoute
  '/_app/team-requests': typeof AppTeamRequestsRoute
  '/_app/teams': typeof AppTeamsRoute
  '/_app/terms': typeof AppTermsRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/deposits': typeof AppAdminDepositsRoute
  '/_app/admin/leaderboard': typeof AppAdminLeaderboardRoute
  '/_app/admin/messages': typeof AppAdminMessagesRoute
  '/_app/admin/notifications': typeof AppAdminNotificationsRoute
  '/_app/admin/payouts': typeof AppAdminPayoutsRoute
  '/_app/admin/profile-shop': typeof AppAdminProfileShopRoute
  '/_app/admin/registrations': typeof AppAdminRegistrationsRoute
  '/_app/admin/site-settings': typeof AppAdminSiteSettingsRoute
  '/_app/admin/spin-wheel': typeof AppAdminSpinWheelRoute
  '/_app/admin/tournaments': typeof AppAdminTournamentsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/spin-wheel/buy': typeof AppSpinWheelBuyRoute
  '/_app/support/$ticketId': typeof AppSupportTicketIdRoute
  '/_app/tournaments/$id': typeof AppTournamentsIdRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/spin-wheel/': typeof AppSpinWheelIndexRoute
  '/_app/support/': typeof AppSupportIndexRoute
  '/_app/tournaments/': typeof AppTournamentsIndexRoute
  '/_app/admin/tickets/$ticketId': typeof AppAdminTicketsTicketIdRoute
  '/_app/admin/tickets/': typeof AppAdminTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anti-cheat'
    | '/chat'
    | '/contact'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/matches'
    | '/my-team'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/profile-shop'
    | '/rules'
    | '/settings'
    | '/signup'
    | '/spin-wheel'
    | '/stats'
    | '/team-chat'
    | '/team-invite'
    | '/team-requests'
    | '/teams'
    | '/terms'
    | '/wallet'
    | '/admin/deposits'
    | '/admin/leaderboard'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/payouts'
    | '/admin/profile-shop'
    | '/admin/registrations'
    | '/admin/site-settings'
    | '/admin/spin-wheel'
    | '/admin/tournaments'
    | '/admin/users'
    | '/spin-wheel/buy'
    | '/support/$ticketId'
    | '/tournaments/$id'
    | '/users/$userId'
    | '/admin/'
    | '/spin-wheel/'
    | '/support/'
    | '/tournaments/'
    | '/admin/tickets/$ticketId'
    | '/admin/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/anti-cheat'
    | '/chat'
    | '/contact'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/matches'
    | '/my-team'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/profile-shop'
    | '/rules'
    | '/settings'
    | '/signup'
    | '/stats'
    | '/team-chat'
    | '/team-invite'
    | '/team-requests'
    | '/teams'
    | '/terms'
    | '/wallet'
    | '/'
    | '/admin/deposits'
    | '/admin/leaderboard'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/payouts'
    | '/admin/profile-shop'
    | '/admin/registrations'
    | '/admin/site-settings'
    | '/admin/spin-wheel'
    | '/admin/tournaments'
    | '/admin/users'
    | '/spin-wheel/buy'
    | '/support/$ticketId'
    | '/tournaments/$id'
    | '/users/$userId'
    | '/admin'
    | '/spin-wheel'
    | '/support'
    | '/tournaments'
    | '/admin/tickets/$ticketId'
    | '/admin/tickets'
  id:
    | '__root__'
    | '/_app'
    | '/_app/anti-cheat'
    | '/_app/chat'
    | '/_app/contact'
    | '/_app/forgot-password'
    | '/_app/leaderboard'
    | '/_app/login'
    | '/_app/matches'
    | '/_app/my-team'
    | '/_app/notifications'
    | '/_app/privacy'
    | '/_app/profile'
    | '/_app/profile-shop'
    | '/_app/rules'
    | '/_app/settings'
    | '/_app/signup'
    | '/_app/spin-wheel'
    | '/_app/stats'
    | '/_app/team-chat'
    | '/_app/team-invite'
    | '/_app/team-requests'
    | '/_app/teams'
    | '/_app/terms'
    | '/_app/wallet'
    | '/_app/'
    | '/_app/admin/deposits'
    | '/_app/admin/leaderboard'
    | '/_app/admin/messages'
    | '/_app/admin/notifications'
    | '/_app/admin/payouts'
    | '/_app/admin/profile-shop'
    | '/_app/admin/registrations'
    | '/_app/admin/site-settings'
    | '/_app/admin/spin-wheel'
    | '/_app/admin/tournaments'
    | '/_app/admin/users'
    | '/_app/spin-wheel/buy'
    | '/_app/support/$ticketId'
    | '/_app/tournaments/$id'
    | '/_app/users/$userId'
    | '/_app/admin/'
    | '/_app/spin-wheel/'
    | '/_app/support/'
    | '/_app/tournaments/'
    | '/_app/admin/tickets/$ticketId'
    | '/_app/admin/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team-requests': {
      id: '/_app/team-requests'
      path: '/team-requests'
      fullPath: '/team-requests'
      preLoaderRoute: typeof AppTeamRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team-invite': {
      id: '/_app/team-invite'
      path: '/team-invite'
      fullPath: '/team-invite'
      preLoaderRoute: typeof AppTeamInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team-chat': {
      id: '/_app/team-chat'
      path: '/team-chat'
      fullPath: '/team-chat'
      preLoaderRoute: typeof AppTeamChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spin-wheel': {
      id: '/_app/spin-wheel'
      path: '/spin-wheel'
      fullPath: '/spin-wheel'
      preLoaderRoute: typeof AppSpinWheelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signup': {
      id: '/_app/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile-shop': {
      id: '/_app/profile-shop'
      path: '/profile-shop'
      fullPath: '/profile-shop'
      preLoaderRoute: typeof AppProfileShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-team': {
      id: '/_app/my-team'
      path: '/my-team'
      fullPath: '/my-team'
      preLoaderRoute: typeof AppMyTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matches': {
      id: '/_app/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forgot-password': {
      id: '/_app/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AppForgotPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anti-cheat': {
      id: '/_app/anti-cheat'
      path: '/anti-cheat'
      fullPath: '/anti-cheat'
      preLoaderRoute: typeof AppAntiCheatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tournaments/': {
      id: '/_app/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof AppTournamentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/': {
      id: '/_app/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof AppSupportIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spin-wheel/': {
      id: '/_app/spin-wheel/'
      path: '/'
      fullPath: '/spin-wheel/'
      preLoaderRoute: typeof AppSpinWheelIndexRouteImport
      parentRoute: typeof AppSpinWheelRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tournaments/$id': {
      id: '/_app/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof AppTournamentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/$ticketId': {
      id: '/_app/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof AppSupportTicketIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spin-wheel/buy': {
      id: '/_app/spin-wheel/buy'
      path: '/buy'
      fullPath: '/spin-wheel/buy'
      preLoaderRoute: typeof AppSpinWheelBuyRouteImport
      parentRoute: typeof AppSpinWheelRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tournaments': {
      id: '/_app/admin/tournaments'
      path: '/admin/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AppAdminTournamentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/spin-wheel': {
      id: '/_app/admin/spin-wheel'
      path: '/admin/spin-wheel'
      fullPath: '/admin/spin-wheel'
      preLoaderRoute: typeof AppAdminSpinWheelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/site-settings': {
      id: '/_app/admin/site-settings'
      path: '/admin/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AppAdminSiteSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/registrations': {
      id: '/_app/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AppAdminRegistrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/profile-shop': {
      id: '/_app/admin/profile-shop'
      path: '/admin/profile-shop'
      fullPath: '/admin/profile-shop'
      preLoaderRoute: typeof AppAdminProfileShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/payouts': {
      id: '/_app/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AppAdminPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/notifications': {
      id: '/_app/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AppAdminNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/messages': {
      id: '/_app/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AppAdminMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/leaderboard': {
      id: '/_app/admin/leaderboard'
      path: '/admin/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AppAdminLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/deposits': {
      id: '/_app/admin/deposits'
      path: '/admin/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AppAdminDepositsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tickets/': {
      id: '/_app/admin/tickets/'
      path: '/admin/tickets'
      fullPath: '/admin/tickets/'
      preLoaderRoute: typeof AppAdminTicketsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tickets/$ticketId': {
      id: '/_app/admin/tickets/$ticketId'
      path: '/admin/tickets/$ticketId'
      fullPath: '/admin/tickets/$ticketId'
      preLoaderRoute: typeof AppAdminTicketsTicketIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSpinWheelRouteChildren {
  AppSpinWheelBuyRoute: typeof AppSpinWheelBuyRoute
  AppSpinWheelIndexRoute: typeof AppSpinWheelIndexRoute
}

const AppSpinWheelRouteChildren: AppSpinWheelRouteChildren = {
  AppSpinWheelBuyRoute: AppSpinWheelBuyRoute,
  AppSpinWheelIndexRoute: AppSpinWheelIndexRoute,
}

const AppSpinWheelRouteWithChildren = AppSpinWheelRoute._addFileChildren(
  AppSpinWheelRouteChildren,
)

interface AppRouteChildren {
  AppAntiCheatRoute: typeof AppAntiCheatRoute
  AppChatRoute: typeof AppChatRoute
  AppContactRoute: typeof AppContactRoute
  AppForgotPasswordRoute: typeof AppForgotPasswordRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppLoginRoute: typeof AppLoginRoute
  AppMatchesRoute: typeof AppMatchesRoute
  AppMyTeamRoute: typeof AppMyTeamRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProfileShopRoute: typeof AppProfileShopRoute
  AppRulesRoute: typeof AppRulesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSignupRoute: typeof AppSignupRoute
  AppSpinWheelRoute: typeof AppSpinWheelRouteWithChildren
  AppStatsRoute: typeof AppStatsRoute
  AppTeamChatRoute: typeof AppTeamChatRoute
  AppTeamInviteRoute: typeof AppTeamInviteRoute
  AppTeamRequestsRoute: typeof AppTeamRequestsRoute
  AppTeamsRoute: typeof AppTeamsRoute
  AppTermsRoute: typeof AppTermsRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminDepositsRoute: typeof AppAdminDepositsRoute
  AppAdminLeaderboardRoute: typeof AppAdminLeaderboardRoute
  AppAdminMessagesRoute: typeof AppAdminMessagesRoute
  AppAdminNotificationsRoute: typeof AppAdminNotificationsRoute
  AppAdminPayoutsRoute: typeof AppAdminPayoutsRoute
  AppAdminProfileShopRoute: typeof AppAdminProfileShopRoute
  AppAdminRegistrationsRoute: typeof AppAdminRegistrationsRoute
  AppAdminSiteSettingsRoute: typeof AppAdminSiteSettingsRoute
  AppAdminSpinWheelRoute: typeof AppAdminSpinWheelRoute
  AppAdminTournamentsRoute: typeof AppAdminTournamentsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppSupportTicketIdRoute: typeof AppSupportTicketIdRoute
  AppTournamentsIdRoute: typeof AppTournamentsIdRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppSupportIndexRoute: typeof AppSupportIndexRoute
  AppTournamentsIndexRoute: typeof AppTournamentsIndexRoute
  AppAdminTicketsTicketIdRoute: typeof AppAdminTicketsTicketIdRoute
  AppAdminTicketsIndexRoute: typeof AppAdminTicketsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAntiCheatRoute: AppAntiCheatRoute,
  AppChatRoute: AppChatRoute,
  AppContactRoute: AppContactRoute,
  AppForgotPasswordRoute: AppForgotPasswordRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppLoginRoute: AppLoginRoute,
  AppMatchesRoute: AppMatchesRoute,
  AppMyTeamRoute: AppMyTeamRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppProfileRoute: AppProfileRoute,
  AppProfileShopRoute: AppProfileShopRoute,
  AppRulesRoute: AppRulesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSignupRoute: AppSignupRoute,
  AppSpinWheelRoute: AppSpinWheelRouteWithChildren,
  AppStatsRoute: AppStatsRoute,
  AppTeamChatRoute: AppTeamChatRoute,
  AppTeamInviteRoute: AppTeamInviteRoute,
  AppTeamRequestsRoute: AppTeamRequestsRoute,
  AppTeamsRoute: AppTeamsRoute,
  AppTermsRoute: AppTermsRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminDepositsRoute: AppAdminDepositsRoute,
  AppAdminLeaderboardRoute: AppAdminLeaderboardRoute,
  AppAdminMessagesRoute: AppAdminMessagesRoute,
  AppAdminNotificationsRoute: AppAdminNotificationsRoute,
  AppAdminPayoutsRoute: AppAdminPayoutsRoute,
  AppAdminProfileShopRoute: AppAdminProfileShopRoute,
  AppAdminRegistrationsRoute: AppAdminRegistrationsRoute,
  AppAdminSiteSettingsRoute: AppAdminSiteSettingsRoute,
  AppAdminSpinWheelRoute: AppAdminSpinWheelRoute,
  AppAdminTournamentsRoute: AppAdminTournamentsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppSupportTicketIdRoute: AppSupportTicketIdRoute,
  AppTournamentsIdRoute: AppTournamentsIdRoute,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppSupportIndexRoute: AppSupportIndexRoute,
  AppTournamentsIndexRoute: AppTournamentsIndexRoute,
  AppAdminTicketsTicketIdRoute: AppAdminTicketsTicketIdRoute,
  AppAdminTicketsIndexRoute: AppAdminTicketsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
