/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppTeamsRouteImport } from './routes/_app/teams'
import { Route as AppSignupRouteImport } from './routes/_app/signup'
import { Route as AppRulesRouteImport } from './routes/_app/rules'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMatchesRouteImport } from './routes/_app/matches'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppAntiCheatRouteImport } from './routes/_app/anti-cheat'
import { Route as AppTournamentsIndexRouteImport } from './routes/_app/tournaments/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppTournamentsIdRouteImport } from './routes/_app/tournaments/$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminTournamentsRouteImport } from './routes/_app/admin/tournaments'
import { Route as AppAdminRegistrationsRouteImport } from './routes/_app/admin/registrations'
import { Route as AppAdminPayoutsRouteImport } from './routes/_app/admin/payouts'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppAntiCheatRoute = AppAntiCheatRouteImport.update({
  id: '/anti-cheat',
  path: '/anti-cheat',
  getParentRoute: () => AppRoute,
} as any)
const AppTournamentsIndexRoute = AppTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppTournamentsIdRoute = AppTournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTournamentsRoute = AppAdminTournamentsRouteImport.update({
  id: '/admin/tournaments',
  path: '/admin/tournaments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRegistrationsRoute = AppAdminRegistrationsRouteImport.update({
  id: '/admin/registrations',
  path: '/admin/registrations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPayoutsRoute = AppAdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/anti-cheat': typeof AppAntiCheatRoute
  '/community': typeof AppCommunityRoute
  '/contact': typeof AppContactRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/login': typeof AppLoginRoute
  '/matches': typeof AppMatchesRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/rules': typeof AppRulesRoute
  '/signup': typeof AppSignupRoute
  '/teams': typeof AppTeamsRoute
  '/wallet': typeof AppWalletRoute
  '/admin/payouts': typeof AppAdminPayoutsRoute
  '/admin/registrations': typeof AppAdminRegistrationsRoute
  '/admin/tournaments': typeof AppAdminTournamentsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/tournaments/$id': typeof AppTournamentsIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/tournaments/': typeof AppTournamentsIndexRoute
}
export interface FileRoutesByTo {
  '/anti-cheat': typeof AppAntiCheatRoute
  '/community': typeof AppCommunityRoute
  '/contact': typeof AppContactRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/login': typeof AppLoginRoute
  '/matches': typeof AppMatchesRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/rules': typeof AppRulesRoute
  '/signup': typeof AppSignupRoute
  '/teams': typeof AppTeamsRoute
  '/wallet': typeof AppWalletRoute
  '/': typeof AppIndexRoute
  '/admin/payouts': typeof AppAdminPayoutsRoute
  '/admin/registrations': typeof AppAdminRegistrationsRoute
  '/admin/tournaments': typeof AppAdminTournamentsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/tournaments/$id': typeof AppTournamentsIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/tournaments': typeof AppTournamentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/anti-cheat': typeof AppAntiCheatRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/matches': typeof AppMatchesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/rules': typeof AppRulesRoute
  '/_app/signup': typeof AppSignupRoute
  '/_app/teams': typeof AppTeamsRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/payouts': typeof AppAdminPayoutsRoute
  '/_app/admin/registrations': typeof AppAdminRegistrationsRoute
  '/_app/admin/tournaments': typeof AppAdminTournamentsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/tournaments/$id': typeof AppTournamentsIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/tournaments/': typeof AppTournamentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anti-cheat'
    | '/community'
    | '/contact'
    | '/leaderboard'
    | '/login'
    | '/matches'
    | '/notifications'
    | '/profile'
    | '/rules'
    | '/signup'
    | '/teams'
    | '/wallet'
    | '/admin/payouts'
    | '/admin/registrations'
    | '/admin/tournaments'
    | '/admin/users'
    | '/tournaments/$id'
    | '/admin/'
    | '/tournaments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/anti-cheat'
    | '/community'
    | '/contact'
    | '/leaderboard'
    | '/login'
    | '/matches'
    | '/notifications'
    | '/profile'
    | '/rules'
    | '/signup'
    | '/teams'
    | '/wallet'
    | '/'
    | '/admin/payouts'
    | '/admin/registrations'
    | '/admin/tournaments'
    | '/admin/users'
    | '/tournaments/$id'
    | '/admin'
    | '/tournaments'
  id:
    | '__root__'
    | '/_app'
    | '/_app/anti-cheat'
    | '/_app/community'
    | '/_app/contact'
    | '/_app/leaderboard'
    | '/_app/login'
    | '/_app/matches'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/rules'
    | '/_app/signup'
    | '/_app/teams'
    | '/_app/wallet'
    | '/_app/'
    | '/_app/admin/payouts'
    | '/_app/admin/registrations'
    | '/_app/admin/tournaments'
    | '/_app/admin/users'
    | '/_app/tournaments/$id'
    | '/_app/admin/'
    | '/_app/tournaments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signup': {
      id: '/_app/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matches': {
      id: '/_app/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anti-cheat': {
      id: '/_app/anti-cheat'
      path: '/anti-cheat'
      fullPath: '/anti-cheat'
      preLoaderRoute: typeof AppAntiCheatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tournaments/': {
      id: '/_app/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof AppTournamentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tournaments/$id': {
      id: '/_app/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof AppTournamentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tournaments': {
      id: '/_app/admin/tournaments'
      path: '/admin/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AppAdminTournamentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/registrations': {
      id: '/_app/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AppAdminRegistrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/payouts': {
      id: '/_app/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AppAdminPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAntiCheatRoute: typeof AppAntiCheatRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppContactRoute: typeof AppContactRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppLoginRoute: typeof AppLoginRoute
  AppMatchesRoute: typeof AppMatchesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRulesRoute: typeof AppRulesRoute
  AppSignupRoute: typeof AppSignupRoute
  AppTeamsRoute: typeof AppTeamsRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminPayoutsRoute: typeof AppAdminPayoutsRoute
  AppAdminRegistrationsRoute: typeof AppAdminRegistrationsRoute
  AppAdminTournamentsRoute: typeof AppAdminTournamentsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppTournamentsIdRoute: typeof AppTournamentsIdRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppTournamentsIndexRoute: typeof AppTournamentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAntiCheatRoute: AppAntiCheatRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppContactRoute: AppContactRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppLoginRoute: AppLoginRoute,
  AppMatchesRoute: AppMatchesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRulesRoute: AppRulesRoute,
  AppSignupRoute: AppSignupRoute,
  AppTeamsRoute: AppTeamsRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminPayoutsRoute: AppAdminPayoutsRoute,
  AppAdminRegistrationsRoute: AppAdminRegistrationsRoute,
  AppAdminTournamentsRoute: AppAdminTournamentsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppTournamentsIdRoute: AppTournamentsIdRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppTournamentsIndexRoute: AppTournamentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
