/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppTermsRouteImport } from './routes/_app/terms'
import { Route as AppTeamsRouteImport } from './routes/_app/teams'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppSignupRouteImport } from './routes/_app/signup'
import { Route as AppRulesRouteImport } from './routes/_app/rules'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMatchesRouteImport } from './routes/_app/matches'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppAntiCheatRouteImport } from './routes/_app/anti-cheat'
import { Route as AppTournamentsIndexRouteImport } from './routes/_app/tournaments/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppTournamentsIdRouteImport } from './routes/_app/tournaments/$id'
import { Route as AppSupportTicketIdRouteImport } from './routes/_app/support.$ticketId'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminTournamentsRouteImport } from './routes/_app/admin/tournaments'
import { Route as AppAdminTicketsRouteImport } from './routes/_app/admin/tickets'
import { Route as AppAdminSetupRouteImport } from './routes/_app/admin/setup'
import { Route as AppAdminRegistrationsRouteImport } from './routes/_app/admin/registrations'
import { Route as AppAdminPayoutsRouteImport } from './routes/_app/admin/payouts'
import { Route as AppAdminNotificationsRouteImport } from './routes/_app/admin/notifications'
import { Route as AppAdminMessagesRouteImport } from './routes/_app/admin/messages'
import { Route as AppAdminLeaderboardRouteImport } from './routes/_app/admin/leaderboard'
import { Route as AppAdminTicketsTicketIdRouteImport } from './routes/_app/admin/tickets.$ticketId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAntiCheatRoute = AppAntiCheatRouteImport.update({
  id: '/anti-cheat',
  path: '/anti-cheat',
  getParentRoute: () => AppRoute,
} as any)
const AppTournamentsIndexRoute = AppTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppTournamentsIdRoute = AppTournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportTicketIdRoute = AppSupportTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AppSupportRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTournamentsRoute = AppAdminTournamentsRouteImport.update({
  id: '/admin/tournaments',
  path: '/admin/tournaments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTicketsRoute = AppAdminTicketsRouteImport.update({
  id: '/admin/tickets',
  path: '/admin/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSetupRoute = AppAdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRegistrationsRoute = AppAdminRegistrationsRouteImport.update({
  id: '/admin/registrations',
  path: '/admin/registrations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPayoutsRoute = AppAdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNotificationsRoute = AppAdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMessagesRoute = AppAdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLeaderboardRoute = AppAdminLeaderboardRouteImport.update({
  id: '/admin/leaderboard',
  path: '/admin/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTicketsTicketIdRoute = AppAdminTicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AppAdminTicketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/anti-cheat': typeof AppAntiCheatRoute
  '/chat': typeof AppChatRoute
  '/contact': typeof AppContactRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/login': typeof AppLoginRoute
  '/matches': typeof AppMatchesRoute
  '/notifications': typeof AppNotificationsRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/rules': typeof AppRulesRoute
  '/signup': typeof AppSignupRoute
  '/support': typeof AppSupportRouteWithChildren
  '/teams': typeof AppTeamsRoute
  '/terms': typeof AppTermsRoute
  '/wallet': typeof AppWalletRoute
  '/admin/leaderboard': typeof AppAdminLeaderboardRoute
  '/admin/messages': typeof AppAdminMessagesRoute
  '/admin/notifications': typeof AppAdminNotificationsRoute
  '/admin/payouts': typeof AppAdminPayoutsRoute
  '/admin/registrations': typeof AppAdminRegistrationsRoute
  '/admin/setup': typeof AppAdminSetupRoute
  '/admin/tickets': typeof AppAdminTicketsRouteWithChildren
  '/admin/tournaments': typeof AppAdminTournamentsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/support/$ticketId': typeof AppSupportTicketIdRoute
  '/tournaments/$id': typeof AppTournamentsIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/tournaments/': typeof AppTournamentsIndexRoute
  '/admin/tickets/$ticketId': typeof AppAdminTicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/anti-cheat': typeof AppAntiCheatRoute
  '/chat': typeof AppChatRoute
  '/contact': typeof AppContactRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/login': typeof AppLoginRoute
  '/matches': typeof AppMatchesRoute
  '/notifications': typeof AppNotificationsRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/rules': typeof AppRulesRoute
  '/signup': typeof AppSignupRoute
  '/support': typeof AppSupportRouteWithChildren
  '/teams': typeof AppTeamsRoute
  '/terms': typeof AppTermsRoute
  '/wallet': typeof AppWalletRoute
  '/': typeof AppIndexRoute
  '/admin/leaderboard': typeof AppAdminLeaderboardRoute
  '/admin/messages': typeof AppAdminMessagesRoute
  '/admin/notifications': typeof AppAdminNotificationsRoute
  '/admin/payouts': typeof AppAdminPayoutsRoute
  '/admin/registrations': typeof AppAdminRegistrationsRoute
  '/admin/setup': typeof AppAdminSetupRoute
  '/admin/tickets': typeof AppAdminTicketsRouteWithChildren
  '/admin/tournaments': typeof AppAdminTournamentsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/support/$ticketId': typeof AppSupportTicketIdRoute
  '/tournaments/$id': typeof AppTournamentsIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/tournaments': typeof AppTournamentsIndexRoute
  '/admin/tickets/$ticketId': typeof AppAdminTicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/anti-cheat': typeof AppAntiCheatRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/matches': typeof AppMatchesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/rules': typeof AppRulesRoute
  '/_app/signup': typeof AppSignupRoute
  '/_app/support': typeof AppSupportRouteWithChildren
  '/_app/teams': typeof AppTeamsRoute
  '/_app/terms': typeof AppTermsRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/leaderboard': typeof AppAdminLeaderboardRoute
  '/_app/admin/messages': typeof AppAdminMessagesRoute
  '/_app/admin/notifications': typeof AppAdminNotificationsRoute
  '/_app/admin/payouts': typeof AppAdminPayoutsRoute
  '/_app/admin/registrations': typeof AppAdminRegistrationsRoute
  '/_app/admin/setup': typeof AppAdminSetupRoute
  '/_app/admin/tickets': typeof AppAdminTicketsRouteWithChildren
  '/_app/admin/tournaments': typeof AppAdminTournamentsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/support/$ticketId': typeof AppSupportTicketIdRoute
  '/_app/tournaments/$id': typeof AppTournamentsIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/tournaments/': typeof AppTournamentsIndexRoute
  '/_app/admin/tickets/$ticketId': typeof AppAdminTicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anti-cheat'
    | '/chat'
    | '/contact'
    | '/leaderboard'
    | '/login'
    | '/matches'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/rules'
    | '/signup'
    | '/support'
    | '/teams'
    | '/terms'
    | '/wallet'
    | '/admin/leaderboard'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/payouts'
    | '/admin/registrations'
    | '/admin/setup'
    | '/admin/tickets'
    | '/admin/tournaments'
    | '/admin/users'
    | '/support/$ticketId'
    | '/tournaments/$id'
    | '/admin/'
    | '/tournaments/'
    | '/admin/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/anti-cheat'
    | '/chat'
    | '/contact'
    | '/leaderboard'
    | '/login'
    | '/matches'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/rules'
    | '/signup'
    | '/support'
    | '/teams'
    | '/terms'
    | '/wallet'
    | '/'
    | '/admin/leaderboard'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/payouts'
    | '/admin/registrations'
    | '/admin/setup'
    | '/admin/tickets'
    | '/admin/tournaments'
    | '/admin/users'
    | '/support/$ticketId'
    | '/tournaments/$id'
    | '/admin'
    | '/tournaments'
    | '/admin/tickets/$ticketId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/anti-cheat'
    | '/_app/chat'
    | '/_app/contact'
    | '/_app/leaderboard'
    | '/_app/login'
    | '/_app/matches'
    | '/_app/notifications'
    | '/_app/privacy'
    | '/_app/profile'
    | '/_app/rules'
    | '/_app/signup'
    | '/_app/support'
    | '/_app/teams'
    | '/_app/terms'
    | '/_app/wallet'
    | '/_app/'
    | '/_app/admin/leaderboard'
    | '/_app/admin/messages'
    | '/_app/admin/notifications'
    | '/_app/admin/payouts'
    | '/_app/admin/registrations'
    | '/_app/admin/setup'
    | '/_app/admin/tickets'
    | '/_app/admin/tournaments'
    | '/_app/admin/users'
    | '/_app/support/$ticketId'
    | '/_app/tournaments/$id'
    | '/_app/admin/'
    | '/_app/tournaments/'
    | '/_app/admin/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signup': {
      id: '/_app/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matches': {
      id: '/_app/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anti-cheat': {
      id: '/_app/anti-cheat'
      path: '/anti-cheat'
      fullPath: '/anti-cheat'
      preLoaderRoute: typeof AppAntiCheatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tournaments/': {
      id: '/_app/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof AppTournamentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tournaments/$id': {
      id: '/_app/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof AppTournamentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/$ticketId': {
      id: '/_app/support/$ticketId'
      path: '/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof AppSupportTicketIdRouteImport
      parentRoute: typeof AppSupportRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tournaments': {
      id: '/_app/admin/tournaments'
      path: '/admin/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AppAdminTournamentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tickets': {
      id: '/_app/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AppAdminTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/setup': {
      id: '/_app/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AppAdminSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/registrations': {
      id: '/_app/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AppAdminRegistrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/payouts': {
      id: '/_app/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AppAdminPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/notifications': {
      id: '/_app/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AppAdminNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/messages': {
      id: '/_app/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AppAdminMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/leaderboard': {
      id: '/_app/admin/leaderboard'
      path: '/admin/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AppAdminLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tickets/$ticketId': {
      id: '/_app/admin/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/admin/tickets/$ticketId'
      preLoaderRoute: typeof AppAdminTicketsTicketIdRouteImport
      parentRoute: typeof AppAdminTicketsRoute
    }
  }
}

interface AppSupportRouteChildren {
  AppSupportTicketIdRoute: typeof AppSupportTicketIdRoute
}

const AppSupportRouteChildren: AppSupportRouteChildren = {
  AppSupportTicketIdRoute: AppSupportTicketIdRoute,
}

const AppSupportRouteWithChildren = AppSupportRoute._addFileChildren(
  AppSupportRouteChildren,
)

interface AppAdminTicketsRouteChildren {
  AppAdminTicketsTicketIdRoute: typeof AppAdminTicketsTicketIdRoute
}

const AppAdminTicketsRouteChildren: AppAdminTicketsRouteChildren = {
  AppAdminTicketsTicketIdRoute: AppAdminTicketsTicketIdRoute,
}

const AppAdminTicketsRouteWithChildren = AppAdminTicketsRoute._addFileChildren(
  AppAdminTicketsRouteChildren,
)

interface AppRouteChildren {
  AppAntiCheatRoute: typeof AppAntiCheatRoute
  AppChatRoute: typeof AppChatRoute
  AppContactRoute: typeof AppContactRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppLoginRoute: typeof AppLoginRoute
  AppMatchesRoute: typeof AppMatchesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRulesRoute: typeof AppRulesRoute
  AppSignupRoute: typeof AppSignupRoute
  AppSupportRoute: typeof AppSupportRouteWithChildren
  AppTeamsRoute: typeof AppTeamsRoute
  AppTermsRoute: typeof AppTermsRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminLeaderboardRoute: typeof AppAdminLeaderboardRoute
  AppAdminMessagesRoute: typeof AppAdminMessagesRoute
  AppAdminNotificationsRoute: typeof AppAdminNotificationsRoute
  AppAdminPayoutsRoute: typeof AppAdminPayoutsRoute
  AppAdminRegistrationsRoute: typeof AppAdminRegistrationsRoute
  AppAdminSetupRoute: typeof AppAdminSetupRoute
  AppAdminTicketsRoute: typeof AppAdminTicketsRouteWithChildren
  AppAdminTournamentsRoute: typeof AppAdminTournamentsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppTournamentsIdRoute: typeof AppTournamentsIdRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppTournamentsIndexRoute: typeof AppTournamentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAntiCheatRoute: AppAntiCheatRoute,
  AppChatRoute: AppChatRoute,
  AppContactRoute: AppContactRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppLoginRoute: AppLoginRoute,
  AppMatchesRoute: AppMatchesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppProfileRoute: AppProfileRoute,
  AppRulesRoute: AppRulesRoute,
  AppSignupRoute: AppSignupRoute,
  AppSupportRoute: AppSupportRouteWithChildren,
  AppTeamsRoute: AppTeamsRoute,
  AppTermsRoute: AppTermsRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminLeaderboardRoute: AppAdminLeaderboardRoute,
  AppAdminMessagesRoute: AppAdminMessagesRoute,
  AppAdminNotificationsRoute: AppAdminNotificationsRoute,
  AppAdminPayoutsRoute: AppAdminPayoutsRoute,
  AppAdminRegistrationsRoute: AppAdminRegistrationsRoute,
  AppAdminSetupRoute: AppAdminSetupRoute,
  AppAdminTicketsRoute: AppAdminTicketsRouteWithChildren,
  AppAdminTournamentsRoute: AppAdminTournamentsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppTournamentsIdRoute: AppTournamentsIdRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppTournamentsIndexRoute: AppTournamentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
